version: '3.3'

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: {}
  alertmanager-data: {}

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9001:9001
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/prometheus_alert.rules:/etc/prometheus/prometheus_alert.rules.yml
      - prometheus_alert.rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana_provisioning.yml:/etc/grafana/provisioning/dashboards/grafana_provisioning.yml
      # - ./monitoring/grafana_node_expoter_dashboard.json:/etc/grafana/provisioning/dashboards/grafana_node_expoter_dashboard.json
      - ./monitoring/grafana_http_dashboard.json:/etc/grafana/provisioning/dashboards/grafana_http_dashboard.json
      - ./monitoring/grafana_datasources.yml:/etc/grafana/provisioning/datasources/grafana_datasources.yml
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - "./monitoring/alertmanager.yml:/monitoring/alertmanager.yml"
    command: --config.file=/monitoring/alertmanager.yml --log.level=debug
    networks:
      - monitoring
