global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/prometheus_alert.rules.yml

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "app"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:6000"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9001"]

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ["alertmanager:9093"]
